phases:
- phase: Windows_Unit_Tests
  queue:
    parallel: 2
    matrix:
      debug:
        configuration: debug
      release: 
        configuration: release
  steps:
    - script: build/scripts/cibuild.cmd -$(configuration) -testDesktop -test32

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\$(configuration)\Logs'
        ArtifactName: 'Build Diagnostic Files $(configuration)'
        publishLocation: Container
      continueOnError: true
      condition: failed()
           
- phase: Windows_Determinism_Test
  steps:
    - script: build/scripts/cibuild.cmd -testDeterminism

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\Debug\Logs'
        ArtifactName: 'Build Determinism Files'
        publishLocation: Container
      continueOnError: true
      condition: failed()
